# Generated by Django 4.2.16 on 2025-08-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_course_name_alter_student_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "verbose_name": "Students name",
                "verbose_name_plural": "Students name",
            },
        ),
    ]
